language: ruby
install:       bundle install --without development:production:deployment --deployment
before_script:
  - cp config/database.yml.example config/database.yml
  - bundle exec rake db:create db:migrate db:test:prepare
rvm:
  - 2.0.0
